.PHONY: compile clean recompile \
        run build docker-run build-code build-all stop

USER     ?= $(shell whoami)
PORT     ?= 8050
WEBAPP   := $(USER)-wcm-webapp
CODE     := $(USER)-wcm-code
RUNTIME  := $(USER)-wcm-runtime

compile:
	python setup.py build_ext --inplace
	rm -fr build

# The reconstruction/ecoli/dataclasses/process/*.py files were generated by
#  write_ode_file.py in Parca code.
# Fireworks writes launcher_20* and block_20*.
# `aesara-cache clear` clears the current $(aesara-cache) cache, not others, and
# leaves 3 small *.delete.me dirs for later in case they're in use, esp. on NFS.
clean:
	rm -fr fixtures cache
	(cd reconstruction/ecoli/dataclasses/process && rm -f equilibrium_odes.py two_component_system_odes*.py)
	find . -name "*.pyc" -exec rm -rf {} +
	find . -name "*.o" -exec rm -fr {} +
	find . -name "*.so" -exec rm -fr {} +
	rm -fr build
	rm -fr launcher_20* block_20*
	if [ "`aesara-cache | xargs du -sm | cut -f1`" -gt 30 ]; then \
		echo "Clearing the aesara-cache since it's larger than threshold."; \
		aesara-cache clear; \
	fi

# Delete just the *.so libraries then (re)compile them.
# This is useful when switching to a different Python virtualenv.
recompile:
	find . -name "*.so" -delete
	make compile

# ── Local development ─────────────────────────────────────────────────────────

# Run the webapp directly — no Docker, hot-reloads on save (fastest dev loop).
run:
	PYTHONPATH="$$PWD" python runscripts/manual/webapp.py \
		--port $(PORT) --docker-image $(CODE) --debug

# Run the webapp inside Docker, mounting ./out/ for simulation data.
docker-run:
	docker run --rm \
		-p $(PORT):8050 \
		-v "$$PWD/out:/wcEcoli/out" \
		-e WEBAPP_PORT=8050 \
		$(WEBAPP)

# Build the webapp image (fast — just copies source onto wcm-code).
build: _require-code-image
	docker build -f cloud/docker/webapp/Dockerfile \
		--build-arg from=$(CODE) \
		-t $(WEBAPP) .

# Rebuild wcm-code (needed when simulation Python/Cython code changes).
build-code: _require-runtime-image
	cloud/locally-build-wcm.sh

# Full rebuild: runtime → code → webapp (slow).
build-all:
	cloud/locally-build-runtime.sh
	cloud/locally-build-wcm.sh
	docker build -f cloud/docker/webapp/Dockerfile \
		--build-arg from=$(CODE) \
		-t $(WEBAPP) .

# Kill any directly-running webapp process.
stop:
	pkill -f "webapp.py" && echo "Stopped." || echo "No webapp process found."

# Internal guards ─────────────────────────────────────────────────────────────
_require-runtime-image:
	@docker image inspect $(RUNTIME) > /dev/null 2>&1 || \
		(echo "$(RUNTIME) not found — run 'make build-all' first" && exit 1)

_require-code-image:
	@docker image inspect $(CODE) > /dev/null 2>&1 || \
		(echo "$(CODE) not found — run 'make build-code' first" && exit 1)
